CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER,
    NAME VARCHAR(50),
    CITY VARCHAR(50),
    SIGNUP_DATE VARCHAR(50),
    TARIFF_ID INTEGER
);

CREATE TABLE MONTHLY_STATS (
    ID INTEGER,
    CUSTOMER_ID INTEGER,
    DATA_USAGE REAL,
    MINUTE_USAGE INTEGER,
    SMS_USAGE INTEGER,
    PAYMENT_STATUS VARCHAR(50)
);

CREATE TABLE TARIFFS (
    TARIFF_ID INTEGER,
    NAME VARCHAR(50),
    MONTHLY_FEE INTEGER,
    DATA_LIMIT INTEGER,
    MINUTE_LIMIT INTEGER,
    SMS_LIMIT INTEGER
);